from typing import Any

from pydantic import BaseModel, Field, field_validator

from app.enums import ToolName


# ==========================================================
# Tool Request
# ==========================================================

class ToolRequest(BaseModel):
    """
    Request generated by the planner for tool execution.
    """

    tool_name: ToolName

    parameters: dict[str, Any] = Field(
        default_factory=dict
    )

    @field_validator("tool_name", mode="before")
    @classmethod
    def normalize_tool_name(cls, value: Any) -> Any:
        from app.utils.planner_parser import resolve_tool_name

        if isinstance(value, str):
            resolved = resolve_tool_name(value)
            if resolved is not None:
                return resolved.value

        return value


# ==========================================================
# Tool Result
# ==========================================================

class ToolResult(BaseModel):
    """
    Standard response returned by every tool.
    """

    success: bool

    tool_name: ToolName

    content: Any = None

    error: str | None = None


# ==========================================================
# Search Models
# ==========================================================

class SearchItem(BaseModel):

    title: str

    url: str

    snippet: str


class SearchResult(BaseModel):

    query: str

    results: list[SearchItem] = Field(default_factory=list)


class CalculatorResult(BaseModel):
    """
    Result returned by the Calculator tool.
    """

    expression: str

    result: str


class FileSystemResult(BaseModel):
    """
    Result returned by the File System tool.
    """

    operation: str

    path: str

    destination: str | None = None

    content: str | None = None

    message: str

    details: dict[str, Any] | None = None


# ==========================================================
# Planner Decision
# ==========================================================

class PlannerDecision(BaseModel):
    """
    Planner output.
    """

    use_tool: bool

    tool_request: ToolRequest | None = None

    reasoning: str = ""

    final_answer: str | None = None



from typing import Any

from pydantic import BaseModel, Field


class ToolMetadata(BaseModel):
    """
    Metadata describing a tool.

    Used by the planner to decide when and how
    a tool should be used.
    """

    description: str

    usage: list[str] = Field(
        default_factory=list
    )

    parameters: dict[str, Any] = Field(
        default_factory=dict
    )

    examples: list[str] = Field(
        default_factory=list
    )

    when_not_to_use: list[str] = Field(
        default_factory=list
    )